services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: 'kazantracks'
      POSTGRES_USER: 'django'
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        - PORT=8000
    environment:
      DJANGO_DEBUG: "${DJANGO_DEBUG:-False}"
      DB_HOST: database
      DB_PASSWORD: "${DB_PASS}"
    depends_on:
      - database

  nginx:
    image: nginx
    environment:
      VIRTUAL_HOST:
      LETSENCRYPT_HOST:
    volumes:
      - ./config:/etc/nginx/conf.d/
      - ./static:/static/
      - images:/images/
    depends_on:
      - web
    networks:
      - nginx-proxy
      - default

volumes:
  images:
    name: "${DEPLOY_ENV:-dev}-images"
  db-data:
    name: "${DEPLOY_ENV:-dev}-routsweb-db"

networks:
  default:
  nginx-proxy:
    external: true
