---
name: dev-deployment
on:
  pull_request:

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.kazantracks.ru
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: django 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo set -euf -o pipefail
            echo cd ~/routsweb
            echo if [[ "${{ github.repository_owner }}" == "Aklenor" ]]; then
            echo   REMOTE=aklenor
            echo else
            echo   REMOTE=origin
            echo fi
            echo git fetch "${REMOTE}" "${{ github.head_ref }}"
            echo git checkout "${REMOTE}/${{ github.head_ref }}"
            echo export VIRTUAL_HOST=dev.kazantracks.ru
            echo export LETSENCRYPT_HOST=$VIRTUAL_HOST
            echo export DEPLOY_ENV=dev
            echo docker compose --project-name dev up --build -d
