---
name: prod-deployment
on:
  branches:    
    - 'main'

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://kazantracks.ru
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: django 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euf -o pipefail
            cd ~/routsweb
            if [[ "${{ github.repository_owner }}" == "Aklenor" ]]; then
              REMOTE=aklenor
            else
              REMOTE=origin
            fi
            git fetch "${REMOTE}" "${{ github.ref_name }}"
            git checkout "${REMOTE}/${{ github.ref_name }}"
            export VIRTUAL_HOST=kazantracks.ru
            export LETSENCRYPT_HOST=$VIRTUAL_HOST
            export DEPLOY_ENV=prod
            docker compose --project prod up --build -d
