version: '3'

services:
  ###############################################################
  #                Our core monitoring stack                    #
  ############################################################### 
  prometheus:
    image: prom/prometheus:main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # We mount a custom prometheus config
      - prom-db:/prometheus

  grafana:                                            # Garafana needs no config file since
    image: grafana/grafana                            # we configure it once it's up
    environment:
      VIRTUAL_HOST:
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
      GF_SERVER_DOMAIN: "${VIRTUAL_HOST}"
      GF_SERVER_HTTP_PORT: 80
      GF_SERVER_PROTOCOL: http
    depends_on: [prometheus]                            
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - default
      - nginx-proxy

  ###############################################################
  #            Agents to collect runtime metric                 #
  ############################################################### 
  nginx-exporter:
    image: bitnami/nginx-exporter:0.10.0
    command: '-nginx.scrape-uri=http://nginx-proxy:8080/stub_status'
    depends_on: [nginx-proxy]
    networks:
      - default
      - nginx-proxy

  node-exporter: 
    image: prom/node-exporter:latest
    container_name: node_exporter
    hostname: "${HOSTNAME}"
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - /:/host:ro

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:                                          # Don't ask me why I mounted all these
    - /:/rootfs:ro                                    # directories. I simply copied these
    - /var/run:/var/run:ro                            # mounts from the documentation.
    - /sys:/sys:ro
    - /dev:/dev:ro
    - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana:
  am-data:
  prom-db:

networks:
  default:
  nginx-proxy:
    external: true
